// packages/svelte/src/lib/components/avatar/anatomy/avatar-image.svelte
<script lang="ts">
    import { mergeProps } from "@zag-js/svelte";
	import { AvatarRootContext } from "../modules/context";
    import type { AvatarImageProps } from "../modules/types";

    const props: AvatarImageProps = $props();
    const rootContext = AvatarRootContext.consume();
    const elementProps =  $derived(mergeProps(rootContext.api.getImageProps(), {
        class: 'base:w-full base:object-cover'
    }, props));
</script>

<img {...elementProps} />

// packages/react/src/components/avatar/anatomy/avatar-image.tsx
'use client';

import { mergeProps } from "@zag-js/react";
import { AvatarRootContext } from "../modules/context";
import type { AvatarImageProps } from "../modules/types";
import { useContext } from "react";

export default function(props: AvatarImageProps ) {
    const rootContext = useContext(AvatarRootContext);
    const elementProps =  mergeProps(rootContext.api.getImageProps(), {
        className: 'base:w-full base:object-cover'
    }, props);
    return <img {...elementProps} />
}
