// packages/svelte/src/lib/components/accordion/anatomy/accordion-indicator.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionRootContext, AccordionItemContext } from '../modules/context';
	import type { AccordionIndicatorProps } from '../modules/types';

	const props: AccordionIndicatorProps = $props();
	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const elementProps = $derived(
		mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), props)
	);
</script>

<div {...elementProps}>
	{@render props.children?.()}
</div>

// packages/react/src/app/components/accordion/components/accordion-indicator.tsx
import { mergeProps } from "@zag-js/react";
import { useContext } from "react";
import { AccordionRootContext, AccordionItemContext } from "../modules/context";
import { AccordionIndicatorProps } from "../modules/types"


export function AccordionIndicator(props: AccordionIndicatorProps) {
    const rootContext = useContext(AccordionRootContext);
    const itemContext = useContext(AccordionItemContext);
    const elementProps =  mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), props);
    return (
        <div {...elementProps}>
            {props.children}
        </div>
    )
}
