// packages/react/src/app/components/accordion/anatomy/accordion.item.tsx
'use client';

import { useContext } from 'react';
import * as accordion from '@zag-js/accordion';
import { mergeProps } from '@zag-js/react';
import type { AccordionItemProps } from '../types';
import { AccordionContext, AccordionItemContext } from '../context';

export function AccordionItem(props: AccordionItemProps) {
    const api = useContext(AccordionContext);
    const [
        zagProps,
        componentProps
    ] = accordion.splitItemProps(props);
    const elementProps =  mergeProps(api.getItemProps(zagProps), componentProps);
    return (
        <AccordionItemContext.Provider value={zagProps}>
            <div {...elementProps}>
                {props.children}
            </div>
        </AccordionItemContext.Provider>
    )
}

// packages/svelte/src/lib/components/accordion/anatomy/accordion.item.svelte
<script lang="ts">
	import { mergeProps } from "@zag-js/svelte";
    import * as accordion from "@zag-js/accordion";
	import type { AccordionItemProps } from "../types";
	import { getContext, setContext } from "svelte";

    const props: AccordionItemProps = $props();
    const [
        zagProps,
        componentProps
    ] = accordion.splitItemProps(props);
    const id = $props.id();
    const api = getContext<accordion.Api>('accordion-context');
    const elementProps =  mergeProps(api.getItemProps(zagProps), {
        className: 'base:grid gap-2'
    }, componentProps);
    setContext('accordion-item-context', zagProps);
</script>

<div {...elementProps}>
    {props.children}
</div>
