// packages/react/src/components/accordion/anatomy/accordion-content.tsx
'use client';

import { useContext } from "react";
import { mergeProps } from "@zag-js/react";
import { AccordionRootContext, AccordionItemContext } from "../modules/context";
import { AccordionContentProps } from "../modules/types";

export default function(props: AccordionContentProps) {
    const rootContext = useContext(AccordionRootContext);
    const itemContext = useContext(AccordionItemContext);
    const {
        children,
        ...restAttributes
    } = props;
    const attributes = mergeProps(rootContext.api.getItemContentProps(itemContext.itemProps), {
        className: 'base:py-2 base:px-4'
    }, restAttributes);
    return (
        <div {...attributes}>
            {children}
        </div>
    )
}

// packages/svelte/src/lib/components/accordion/anatomy/accordion-content.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionItemContext, AccordionRootContext } from '../modules/context';
	import type { AccordionContentProps } from '../modules/types';

	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const props: AccordionContentProps = $props();
	const { children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getItemContentProps(itemContext.itemProps),
			{
				class: 'base:py-2 base:px-4'
			},
			restAttributes
		)
	);
</script>

<div {...attributes}>
	{@render children?.()}
</div>
