// packages/react/src/app/components/accordion/components/accordion-item.tsx
'use client';

import { useContext } from 'react';
import * as accordion from '@zag-js/accordion';
import { mergeProps } from '@zag-js/react';
import type { AccordionItemProps } from '../modules/types';
import { AccordionRootContext, AccordionItemContext } from '../modules/context';

export function AccordionItem(props: AccordionItemProps) {
    const rootContext = useContext(AccordionRootContext);
    const [
        itemProps,
        componentProps
    ] = accordion.splitItemProps(props);
    const elementProps =  mergeProps(rootContext.api.getItemProps(itemProps), componentProps);
    return (
        <AccordionItemContext.Provider value={{ itemProps }}>
            <div {...elementProps}>
                {props.children}
            </div>
        </AccordionItemContext.Provider>
    )
}

// packages/svelte/src/lib/components/accordion/anatomy/accordion-item.svelte
<script lang="ts">
	import { mergeProps } from "@zag-js/svelte";
    import * as accordion from "@zag-js/accordion";
	import { AccordionItemContext, AccordionRootContext } from "../modules/context";
    import type { AccordionItemProps } from "../modules/types";

    const props: AccordionItemProps = $props();
    const [
        itemProps,
        componentProps
    ] = $derived(accordion.splitItemProps(props));
    const rootContext = AccordionRootContext.consume();
    const elementProps =  $derived(mergeProps(rootContext.api.getItemProps(itemProps), {
        class: 'base:grid gap-2'
    }, componentProps));
    AccordionItemContext.provide({
        get itemProps() {
            return itemProps;
        }
    });
</script>

<div {...elementProps}>
    {@render props.children?.()}
</div>
