// packages/react/src/app/components/accordion/anatomy/accordion-trigger.tsx
'use client';

import { useContext } from "react";
import { mergeProps } from "@zag-js/react";
import { AccordionRootContext, AccordionItemContext } from "../modules/context";
import type { AccordionTriggerProps } from "../modules/types";

export function AccordionTrigger(props: AccordionTriggerProps) {
    const rootContext = useContext(AccordionRootContext);
    const itemContext = useContext(AccordionItemContext);
    const elementProps =  mergeProps(rootContext.api.getItemTriggerProps(itemContext.itemProps), {
        className: 'base:w-full base:text-start base:hover:preset-tonal-primary base:py-2 base:px-4 base:rounded-base base:flex base:justify-between base:items-center'
    }, props);
    return (
        <button {...elementProps}>
            {props.children}
        </button>
    )
}

// packages/svelte/src/lib/components/accordion/anatomy/accordion-trigger.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionItemContext, AccordionRootContext } from '../modules/context';
	import type { AccordionTriggerProps } from '../modules/types';

	const props: AccordionTriggerProps = $props();
	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const elementProps = $derived(
		mergeProps(
			rootContext.api.getItemTriggerProps(itemContext.itemProps),
			{
				class:
					'base:w-full base:text-start base:hover:preset-tonal-primary base:py-2 base:px-4 base:rounded-base base:flex base:justify-between base:items-center'
			},
			props
		)
	);
</script>

<button {...elementProps}>
	{@render props.children?.()}
</button>
