// packages/svelte/src/lib/components/accordion/anatomy/accordion-root.svelte
<script lang="ts">
	import { mergeProps, normalizeProps, useMachine } from "@zag-js/svelte";
    import * as accordion from "@zag-js/accordion";
	import { AccordionRootContext } from "../modules/context";
    import type { AccordionRootProps } from "../modules/types";

    const props: AccordionRootProps = $props();
    const [
        machineProps,
        componentProps
    ] = $derived(accordion.splitProps(props));
    const id = $props.id();
    const service = useMachine(accordion.machine, () => ({ 
        id: id,
        ...machineProps
    }));
    const api = $derived(accordion.connect(service, normalizeProps));
    const elementProps =  $derived(mergeProps(api.getRootProps(), {
        class: 'base:grid base:gap-2'
    }, componentProps));
    AccordionRootContext.provide({
        get api() {
            return api;
        },
    });
</script>

<div {...elementProps}>
    {@render props.children?.()}
</div>

// packages/react/src/app/components/accordion/anatomy/accordion-root.tsx
'use client';

import { useId } from 'react';
import * as accordion from '@zag-js/accordion';
import { useMachine, normalizeProps, mergeProps } from '@zag-js/react';
import { AccordionRootContext } from '../modules/context';
import type { AccordionRootProps } from '../modules/types';

export function AccordionRoot(props: AccordionRootProps) {
    const [
        zagProps,
        componentProps
    ] = accordion.splitProps(props);
    const service = useMachine(accordion.machine, { 
        id: useId(),
        ...zagProps
    });
    const api = accordion.connect(service, normalizeProps);
    const elementProps =  mergeProps(api.getRootProps(), {
        className: 'base:grid base:gap-2'
    }, componentProps);
    return (
        <AccordionRootContext.Provider value={{ api }}>
            <div {...elementProps}>
                {props.children}
            </div>
        </AccordionRootContext.Provider>
    )
}
