// packages/svelte/src/lib/components/accordion/anatomy/accordion.svelte
<script lang="ts">
	import { mergeProps, normalizeProps, useMachine } from "@zag-js/svelte";
    import * as accordion from "@zag-js/accordion";
	import type { AccordionProps } from "../types";
	import { setContext } from "svelte";

    const props: AccordionProps = $props();
    const [
        zagProps,
        componentProps
    ] = accordion.splitProps(props);
    const id = $props.id();
    const service = useMachine(accordion.machine, { 
        id: id,
        ...zagProps
    });
    const api = accordion.connect(service, normalizeProps);
    const elementProps =  mergeProps(api.getRootProps(), {
        className: 'base:grid gap-2'
    }, componentProps);
    setContext('accordion-context', api);
</script>

<div {...elementProps}>
    {props.children}
</div>

// packages/react/src/app/components/accordion/anatomy/accordion.tsx
'use client';

import { useId } from 'react';
import * as accordion from '@zag-js/accordion';
import { useMachine, normalizeProps, mergeProps } from '@zag-js/react';
import { AccordionContext } from '../context';
import type { AccordionProps } from '../types';

export function Accordion(props: AccordionProps) {
    const [
        zagProps,
        componentProps
    ] = accordion.splitProps(props);
    const service = useMachine(accordion.machine, { 
        id: useId(),
        ...zagProps
    });
    const api = accordion.connect(service, normalizeProps);
    const elementProps =  mergeProps(api.getRootProps(), {
        className: 'base:grid base:gap-2'
    }, componentProps);
    return (
        <AccordionContext.Provider value={api}>
            <div {...elementProps}>
                {props.children}
            </div>
        </AccordionContext.Provider>
    )
}
