// packages/svelte/src/lib/components/accordion/anatomy/accordion-content.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionItemContext, AccordionRootContext } from '../modules/context';
	import type { AccordionContentProps } from '../modules/types';

	const props: AccordionContentProps = $props();
	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const elementProps = $derived(
		mergeProps(
			rootContext.api.getItemContentProps(itemContext.itemProps),
			{
				class: 'base:py-2 base:px-4'
			},
			props
		)
	);
</script>

<div {...elementProps}>
	{@render props.children?.()}
</div>

// packages/react/src/app/components/accordion/anatomy/accordion-content.tsx
'use client';

import { useContext } from "react";
import { mergeProps } from "@zag-js/react";
import { AccordionRootContext, AccordionItemContext } from "../modules/context";
import { AccordionContentProps } from "../modules/types";

export function AccordionContent(props: AccordionContentProps) {
    const rootContext = useContext(AccordionRootContext);
    const itemContext = useContext(AccordionItemContext);
    const elementProps =  mergeProps(rootContext.api.getItemContentProps(itemContext.itemProps), {
        className: 'base:py-2 base:px-4'
    }, props);
    return (
        <div {...elementProps}>
            {props.children}
        </div>
    )
}
