// playgrounds/svelte/src/lib/components/accordion/anatomy/accordion.content.svelte
<script lang="ts">
    import * as accordion from "@zag-js/accordion";
    import { mergeProps } from "@zag-js/svelte";
	import { getContext } from "svelte";
    import type { AccordionContentProps } from "../types";

    const props: AccordionContentProps = $props();
    const api = getContext<accordion.Api>('accordion-context');
    const itemProps = getContext<accordion.ItemProps>('accordion-item-context');
    const elementProps =  mergeProps(api.getItemContentProps(itemProps), {
        className: 'base:py-2 base:px-4'
    }, props);
</script>

<div {...elementProps}>
    {@render props.children?.()}
</div>

// packages/react/src/app/components/accordion/anatomy/accordion.content.tsx
'use client';

import { useContext } from "react";
import { mergeProps } from "@zag-js/react";
import { AccordionContext, AccordionItemContext } from "../context";
import { AccordionContentProps } from "../types";

export function AccordionContent(props: AccordionContentProps) {
    const api = useContext(AccordionContext);
    const itemProps = useContext(AccordionItemContext);
    const elementProps =  mergeProps(api.getItemContentProps(itemProps), {
        className: 'base:py-2 base:px-4'
    }, props);
    return (
        <div {...elementProps}>
            {props.children}
        </div>
    )
}
