// packages/svelte/src/lib/components/accordion/anatomy/accordion.trigger.svelte
<script lang="ts">
    import * as accordion from "@zag-js/accordion";
    import { mergeProps } from "@zag-js/svelte";
	import { getContext } from "svelte";
    import type { AccordionTriggerProps } from "../types";

    const props: AccordionTriggerProps = $props();
    const accordionContext = getContext<{ api: accordion.Api }>('accordion-context');
    const accordionItemContext = getContext<{ itemProps: accordion.ItemProps }>('accordion-item-context');
    const elementProps =  $derived(mergeProps(accordionContext.api.getItemTriggerProps(accordionItemContext.itemProps), {
        class: 'base:w-full base:text-start base:hover:preset-tonal-primary base:py-2 base:px-4 base:rounded-base base:flex base:justify-between base:items-center'
    }, props));
</script>

<button {...elementProps}>
    {@render props.children?.()}
</button>

// packages/react/src/app/components/accordion/anatomy/accordion.trigger.tsx
'use client';

import { useContext } from "react";
import { mergeProps } from "@zag-js/react";
import { AccordionContext, AccordionItemContext } from "../context";
import type { AccordionTriggerProps } from "../types";

export function AccordionTrigger(props: AccordionTriggerProps) {
    const api = useContext(AccordionContext);
    const itemProps = useContext(AccordionItemContext);
    const elementProps =  mergeProps(api.getItemTriggerProps(itemProps), {
        className: 'base:w-full base:text-start base:hover:preset-tonal-primary base:py-2 base:px-4 base:rounded-base base:flex base:justify-between base:items-center'
    }, props);
    return (
        <button {...elementProps}>
            {props.children}
        </button>
    )
}
