// packages/react/src/app/accordion/page.tsx
'use client';

import { useState } from "react";
import { Accordion } from "../../components/accordion";

export default function() {
  const items = [1, 2, 3];
  const [value, setValue] = useState(["item-1"]);
  return (
    <Accordion value={value} onValueChange={(details) => setValue(details.value)}>
      {items.map((item) => (
        <Accordion.Item key={item} value={`item-${item}`}>
          <Accordion.Trigger>
            Item {item}
            <Accordion.Indicator>
              {value.includes(`item-${item}`) ? '-' : '+'}
            </Accordion.Indicator>
          </Accordion.Trigger>
          <Accordion.Content>
            Content for item {item}
          </Accordion.Content>
        </Accordion.Item>
      ))}
    </Accordion>
  );
}

// packages/svelte/src/routes/accordion/+page.svelte
<script lang="ts">
    import { Accordion } from "$lib/components/accordion";

    const items = [1, 2, 3];
    let value = $state(['item-1'])
</script>


<Accordion value={value} onValueChange={(details) => (value = details.value)}>
  {#each items as item}
    <Accordion.Item value={`item-${item}`}>
        <Accordion.Trigger>
          Item {item}
          <Accordion.Indicator>
            {value.includes(`item-${item}`) ? '-' : '+'}
          </Accordion.Indicator>
        </Accordion.Trigger>
        <Accordion.Content>
          Content for item {item}
        </Accordion.Content>
      </Accordion.Item>
    {/each}
</Accordion>
