// packages/svelte/src/lib/components/accordion/anatomy/accordion-item.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import * as accordion from '@zag-js/accordion';
	import { AccordionItemContext, AccordionRootContext } from '../modules/context';
	import type { AccordionItemProps } from '../modules/types';

	const rootContext = AccordionRootContext.consume();

	const props: AccordionItemProps = $props();
	const [itemProps, componentProps] = $derived(accordion.splitItemProps(props));
	const { children, ...restAttributes } = $derived(componentProps);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getItemProps(itemProps),
			{
				class: 'base:grid gap-2'
			},
			restAttributes
		)
	);
	AccordionItemContext.provide({
		get itemProps() {
			return itemProps;
		}
	});
</script>

<div {...attributes}>
	{@render children?.()}
</div>

// packages/react/src/components/accordion/anatomy/accordion-item.tsx
'use client';

import { useContext } from 'react';
import * as accordion from '@zag-js/accordion';
import { mergeProps } from '@zag-js/react';
import type { AccordionItemProps } from '../modules/types';
import { AccordionRootContext, AccordionItemContext } from '../modules/context';

export default function(props: AccordionItemProps) {
    const rootContext = useContext(AccordionRootContext);
    const [
        itemProps,
        componentProps
    ] = accordion.splitItemProps(props);
    const { children, ...restAttributes } = componentProps;
    const attributes =  mergeProps(rootContext.api.getItemProps(itemProps), restAttributes);
    return (
        <AccordionItemContext.Provider value={{ itemProps }}>
            <div {...attributes}>
                {children}
            </div>
        </AccordionItemContext.Provider>
    )
}
