// packages/svelte/src/lib/components/accordion/anatomy/accordion-indicator.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionRootContext, AccordionItemContext } from '../modules/context';
	import type { AccordionIndicatorProps } from '../modules/types';

	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const props: AccordionIndicatorProps = $props();
	const { children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), restAttributes)
	);
</script>

<div {...attributes}>
	{@render children?.()}
</div>

// packages/react/src/components/accordion/anatomy/accordion-indicator.tsx
import { mergeProps } from "@zag-js/react";
import { useContext } from "react";
import { AccordionRootContext, AccordionItemContext } from "../modules/context";
import { AccordionIndicatorProps } from "../modules/types"


export default function(props: AccordionIndicatorProps) {
    const rootContext = useContext(AccordionRootContext);
    const itemContext = useContext(AccordionItemContext);
    const {
        children,
        ...restAttributes
    } = props;
    const attributes =  mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), restAttributes);
    return (
        <div {...attributes}>
            {children}
        </div>
    )
}
