// packages/svelte/src/lib/components/accordion/anatomy/accordion.indicator.svelte
<script lang="ts">
    import * as accordion from "@zag-js/accordion";
    import { mergeProps } from "@zag-js/svelte";
	import { getContext } from "svelte";
    import type {  AccordionIndicatorProps } from "../types";

    const props: AccordionIndicatorProps = $props();
    const accordionContext = getContext<{ api: accordion.Api }>('accordion-context');
    const accordionItemContext = getContext<{ itemProps: accordion.ItemProps }>('accordion-item-context');
    const elementProps = $derived(mergeProps(accordionContext.api.getItemIndicatorProps(accordionItemContext.itemProps), props));
</script>

<div {...elementProps}>
    {@render props.children?.()}
</div>

// playgrounds/react/src/app/components/accordion/anatomy/accordion.indicator.tsx
import { mergeProps } from "@zag-js/react";
import { useContext } from "react";
import { AccordionContext, AccordionItemContext } from "../context";
import { AccordionIndicatorProps } from "../types"


export function AccordionIndicator(props: AccordionIndicatorProps) {
    const api = useContext(AccordionContext);
    const itemProps = useContext(AccordionItemContext);
    const elementProps =  mergeProps(api.getItemIndicatorProps(itemProps), props);
    return (
        <div {...elementProps}>
            {props.children}
        </div>
    )
}
