// packages/react/src/components/avatar/anatomy/avatar-fallback.tsx
'use client';

import { mergeProps } from "@zag-js/react";
import { AvatarRootContext } from "../modules/context";
import type { AvatarFallbackProps } from "../modules/types";
import { useContext } from "react";

export default function(props: AvatarFallbackProps) {
    const rootContext = useContext(AvatarRootContext);
    const {
        children,
        ...restAttributes
    } = props;
    const attributes = mergeProps(rootContext.api.getFallbackProps(), {
        className: 'base:size-full base:flex base:justify-center base:items-center'
    }, restAttributes);
    return (
        <span {...attributes}>
            {children}
        </span>
    )
}

// packages/svelte/src/lib/components/avatar/anatomy/avatar-fallback.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AvatarRootContext } from '../modules/context';
	import type { AvatarFallbackProps } from '../modules/types';

	const rootContext = AvatarRootContext.consume();
	const props: AvatarFallbackProps = $props();
	const { children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getFallbackProps(),
			{
				class: 'base:size-full base:flex base:justify-center base:items-center'
			},
			restAttributes
		)
	);
</script>

<span {...attributes}>
	{@render children?.()}
</span>
